import micromatch from 'micromatch';
import { File, FileDao } from "../dao/FileDao";
import { FatalProcessingError } from './AttachmentParserService';
import { AUTOGENERATED_MARKER } from '../utils/constants';
import { ConversionStatusTracker } from './ConversionStatusTracker';

export interface ConversionConfig {
    indexFolder: string;
    sourceExtension: string;
    targetExtension: string;
    fileFilter?: string;
}

export abstract class BaseConverterService {
    private tracker?: ConversionStatusTracker;

    constructor(
        protected fileDao: FileDao,
        protected config: ConversionConfig
    ) {}

    setStatusTracker(tracker: ConversionStatusTracker): void {
        this.tracker = tracker;
    }

    private isRelativeIndexFolder(): boolean {
        return this.config.indexFolder.startsWith('./') || this.config.indexFolder.startsWith('../');
    }

    async convertFiles(): Promise<void> {
        try {
            if (!this.isRelativeIndexFolder()) {
                await this.fileDao.createFolder(this.config.indexFolder);
            }

            const allFiles = await this.fileDao.getFiles();
            const filteredPaths = this.config.fileFilter
                ? new Set(micromatch(allFiles.map(f => f.path), this.config.fileFilter))
                : null;
            const sourceFiles = allFiles.filter(f =>
                f.path.endsWith(this.config.sourceExtension) &&
                (!filteredPaths || filteredPaths.has(f.path))
            );
            this.tracker?.initFiles(sourceFiles.map(f => f.path));
            const convertedFiles = this.findConvertedFileCandidates(allFiles, sourceFiles);

            const [removedFiles, createdFiles, modifiedFiles] = await Promise.all([
                this.removeOrphanedFiles(convertedFiles, sourceFiles),
                this.createConvertedFiles(sourceFiles, convertedFiles),
                this.modifyConvertedFiles(sourceFiles, convertedFiles),
            ]);

            this.logConversionResults(removedFiles, createdFiles, modifiedFiles, sourceFiles.length);
        } catch (error) {
            console.error('Error during conversion:', error);
            
            if (error instanceof FatalProcessingError) {
                throw error;
            }
        }
    }

    protected abstract convertContent(source: File): Promise<string>;

    protected getSourceName(file: File): string {
        return file.name.slice(0, -this.config.targetExtension.length) + this.config.sourceExtension;
    }

    protected getConvertedFilePath(sourcePath: string): string {
        const sourceName = sourcePath.split('/').pop()!;
        const sourceDir = sourcePath.includes('/')
            ? sourcePath.split('/').slice(0, -1).join('/')
            : '';
        const outputFilename = sourceName.slice(0, -this.config.sourceExtension.length) + this.config.targetExtension;
        const indexFolder = this.config.indexFolder;

        if (this.isRelativeIndexFolder()) {
            const resolvedDir = this.resolveRelativeDir(sourceDir, indexFolder);
            return resolvedDir ? `${resolvedDir}/${outputFilename}` : outputFilename;
        }

        // Vault-root-relative: normalize leading/trailing slashes
        const normalized = indexFolder.replace(/^\/+/, '').replace(/\/+$/, '');
        return normalized ? `${normalized}/${outputFilename}` : outputFilename;
    }

    private resolveRelativeDir(sourceDir: string, indexFolder: string): string {
        const parts = sourceDir ? sourceDir.split('/') : [];
        let remaining = indexFolder;

        while (remaining.startsWith('../')) {
            if (parts.length > 0) parts.pop();
            remaining = remaining.slice(3);
        }
        if (remaining.startsWith('./')) {
            remaining = remaining.slice(2);
        }
        if (remaining) parts.push(remaining);
        return parts.join('/');
    }

    private findConvertedFileCandidates(allFiles: File[], sourceFiles: File[]): File[] {
        if (!this.isRelativeIndexFolder()) {
            const normalized = this.config.indexFolder.replace(/^\/+/, '').replace(/\/+$/, '');
            return allFiles.filter(f =>
                f.path.startsWith(`${normalized}/`) &&
                f.path.endsWith(this.config.targetExtension)
            );
        }

        // Relative indexFolder: derive output dirs from current source files.
        // When no sources remain (all deleted), fall back to scanning all files
        // with the target extension — the content-marker check in deleteFile
        // acts as the safety net against deleting user-created files.
        const outputDirs = new Set(
            sourceFiles.map(source => {
                const outputPath = this.getConvertedFilePath(source.path);
                return outputPath.includes('/')
                    ? outputPath.split('/').slice(0, -1).join('/')
                    : '';
            })
        );

        return allFiles.filter(f => {
            if (!f.path.endsWith(this.config.targetExtension)) return false;
            if (sourceFiles.length === 0) return true;
            const dir = f.path.includes('/')
                ? f.path.split('/').slice(0, -1).join('/')
                : '';
            return outputDirs.has(dir);
        });
    }

    protected async removeOrphanedFiles(convertedFiles: File[], sourceFiles: File[]): Promise<string[]> {
        const sourceNames = new Set(sourceFiles.map(f => f.name));

        const removedFiles = convertedFiles
            .filter(convertedFile => !sourceNames.has(this.getSourceName(convertedFile)))
            .map(async convertedFile => {
                try {
                    await this.fileDao.deleteFile(convertedFile.path);
                    return convertedFile.path;
                } catch (error) {
                    console.error(`Failed to remove converted file ${convertedFile.path}:`, error);
                    return null;
                }
            });

        return (await Promise.all(removedFiles)).filter(Boolean) as string[];
    }

    protected async createConvertedFiles(sourceFiles: File[], convertedFiles: File[]): Promise<{
        count: number;
        files: string[]
    }> {
        const convertedNames = new Set(convertedFiles.map(f => this.getSourceName(f)));

        const processedNames = [];
        for (const source of sourceFiles.filter(source => !convertedNames.has(source.name))) {
            try {
                this.tracker?.setStatus(source.path, 'processing');
                const targetPath = this.getConvertedFilePath(source.path);
                await this.convertAndSave(source, targetPath);
                this.tracker?.setStatus(source.path, 'done');
                processedNames.push(source.name);
            } catch (error) {
                const message = error instanceof Error ? error.message : String(error);
                this.tracker?.setStatus(source.path, 'error', message);
                if (error instanceof FatalProcessingError) {
                    throw error;
                }
                console.error(`Error processing file ${source.name}:`, error);
            }
        }
        return { count: processedNames.length, files: processedNames };
    }

    protected async modifyConvertedFiles(sourceFiles: File[], convertedFiles: File[]): Promise<{
        count: number;
        files: string[]
    }> {
        const convertedFileMap = new Map(
            convertedFiles.map(convertedFile => [
                this.getSourceName(convertedFile),
                convertedFile
            ])
        );

        const modifiedFileNames = [];
        for (const source of sourceFiles) {
            const convertedFile = convertedFileMap.get(source.name);
            if (convertedFile && source.modifiedTime >= convertedFile.modifiedTime) {
                try {
                    this.tracker?.setStatus(source.path, 'processing');
                    const targetPath = this.getConvertedFilePath(source.path);
                    await this.convertAndSave(source, targetPath);
                    this.tracker?.setStatus(source.path, 'done');
                    modifiedFileNames.push(source.name);
                } catch (error) {
                    const message = error instanceof Error ? error.message : String(error);
                    this.tracker?.setStatus(source.path, 'error', message);
                    if (error instanceof FatalProcessingError) {
                        throw error;
                    }
                    console.error(`Error processing file ${source.name}:`, error);
                }
            } else {
                this.tracker?.setStatus(source.path, 'done');
            }
        }

        return { count: modifiedFileNames.length, files: modifiedFileNames };
    }

    protected async convertAndSave(source: File, targetPath: string): Promise<void> {
        const newContent = await this.convertContent(source);
        let finalContent = newContent;

        try {
            const existing = await this.fileDao.readFile(targetPath);
            if (existing && existing.includes(AUTOGENERATED_MARKER)) {
                const [userZone] = existing.split(AUTOGENERATED_MARKER);
                const [, autoZone] = newContent.split(AUTOGENERATED_MARKER);
                finalContent = `${userZone}${AUTOGENERATED_MARKER}${autoZone}`;
            }
        } catch {
            // file doesn't exist yet — use newContent as-is
        }

        await this.fileDao.createOrUpdateFile(targetPath, finalContent);
    }

    protected logConversionResults(removedFiles: string[], createdFiles: {
        count: number;
        files: string[]
    }, modifiedFiles: { count: number; files: string[] }, totalFiles: number): void {
        console.log(
            `File conversion completed successfully\n` +
            `Total files processed ${createdFiles.count + modifiedFiles.count + removedFiles.length}/${totalFiles}\n` +
            `Created files ${createdFiles.count}\n` +
            (createdFiles.count > 0 ?
                `  ${createdFiles.files.map(f => `- ${f.replace(this.config.sourceExtension, '')}`).join('\n  ')}\n` : '') +
            `Modified files ${modifiedFiles.count}\n` +
            (modifiedFiles.count > 0 ?
                `  ${modifiedFiles.files.map(f => `- ${f.replace(this.config.sourceExtension, '')}`).join('\n  ')}\n` : '') +
            `Deleted files ${removedFiles.length}\n` +
            (removedFiles.length > 0 ?
                `  ${removedFiles.map(f => `- ${f.replace(`${this.config.indexFolder}/`, '').replace(this.config.targetExtension, '')}`).join('\n  ')}\n` : '')
        );
    }
} 