import { convertCanvasToMd } from '../utils/canvasToMd';
import { FileDao, File } from "../dao/FileDao";
import { CanvasServiceConfig } from "./CanvasServiceConfig";
import { BaseConverterService } from './BaseConverterService';
import { AUTOGENERATED_MARKER } from '../utils/constants';

export class CanvasService extends BaseConverterService {
	constructor(fileDao: FileDao, config: CanvasServiceConfig) {
		super(fileDao, {
			indexFolder: config.indexFolder,
			sourceExtension: '.canvas',
			targetExtension: config.canvasPostfix,
			fileFilter: config.fileFilter
		});
	}

	protected async convertContent(source: File): Promise<string> {
		const rawContent = await source.getContent();
		const transcript = convertCanvasToMd(rawContent);
		return `# Notes

# Content

File: [${source.name}](${source.path})

![[${source.path}]]

> Feel free to write custom notes ABOVE this line, they will be preserved.
> Please note: Deleting the original file will delete this file.

${AUTOGENERATED_MARKER}
# Transcript

${transcript}`;
	}
}
