import { BaseConverterService } from './BaseConverterService';
import { FileDao, File } from "../dao/FileDao";
import { AUTOGENERATED_MARKER } from "../utils/constants";
import { AttachmentParserService } from './AttachmentParserService';

export class PdfConverterService extends BaseConverterService {
    constructor(
        fileDao: FileDao,
        indexFolder: string,
        private parser: AttachmentParserService,
        fileFilter?: string
    ) {
        super(fileDao, {
            indexFolder,
            sourceExtension: '.pdf',
            targetExtension: '.pdf.md',
            fileFilter
        });
    }

    protected async convertContent(source: File): Promise<string> {
        const content = await this.parser.parseAttachmentContent(source.sizeInMB, () => source.getBinaryContent(), source.path);
        return `# Notes

# Content

File: [${source.name}](${source.path})

![[${source.path}#height=500]]

> Feel free to write custom notes ABOVE this line, they will be preserved.
> Please note: Deleting the original file will delete this file.

${AUTOGENERATED_MARKER}
# Transcript

${content}`;
    }

    override async convertFiles(): Promise<void> {
        if (!this.parser.validateApiKey()) {
            console.warn('No Google API key configured - PDF parsing will be skipped');
            return;
        }
        await super.convertFiles();

    }
} 