export const WEBPAGE_TEMPLATE = "![Web Page]({element})";

export const CARD_TEMPLATE = "{element}\n___";

export const NOTE_TEMPLATE = "![[{element}]]";

export const MEDIA_TEMPLATE = "![[{element}|500]]";

export const AUTOGENERATED_MARKER = "<!--auto-generate-content-below-->";
