import { beforeEach, describe, expect, it } from 'vitest';
import { PngConverterService } from '../../src/service/PngConverterService';
import { FileDaoImpl } from '../../src/dao/FileDaoImpl';
import { InMemoryFileAdapter } from '../dao/InMemoryFileAdapter';
import { AttachmentParserService } from '../../src/service/AttachmentParserService';
import { AUTOGENERATED_MARKER } from '../../src/utils/constants';
import { createTestImageFile, readTestFile } from '../utils/testFileUtils';

const MOCK_TRANSCRIPT = 'Mock transcript content';

const mockParser: AttachmentParserService = {
    validateApiKey: () => true,
    parseAttachmentContent: async () => MOCK_TRANSCRIPT,
};

describe('Integration Test: Image Converter (fast, mock parser)', () => {
    let fileAdapter: InMemoryFileAdapter;
    let fileDao: FileDaoImpl;
    let pngConverter: PngConverterService;

    beforeEach(() => {
        fileAdapter = new InMemoryFileAdapter();
        fileDao = new FileDaoImpl(fileAdapter);
        pngConverter = new PngConverterService(fileDao, 'index', mockParser);
    });

    it('skips conversion when API key is not valid', async () => {
        const noKeyParser: AttachmentParserService = {
            validateApiKey: () => false,
            parseAttachmentContent: async () => 'should not be called',
        };
        const converter = new PngConverterService(fileDao, 'index', noKeyParser);
        await createTestImageFile(fileAdapter, 'test-image.png');
        await converter.convertFiles();

        await expect(fileAdapter.read('index/test-image.png.md')).rejects.toThrow();
    });

    it('removes orphaned index file when source image is deleted', async () => {
        await createTestImageFile(fileAdapter, 'test-image.png');
        await fileDao.createOrUpdateFile('index/test-image.png.md', `${AUTOGENERATED_MARKER}\n# Transcript\n${MOCK_TRANSCRIPT}`);

        await fileAdapter.delete('test-image.png');
        await pngConverter.convertFiles();

        await expect(fileAdapter.read('index/test-image.png.md')).rejects.toThrow();
    });

    it('preserves user notes above the marker when image is re-indexed', async () => {
        await createTestImageFile(fileAdapter, 'test-image.png');
        await pngConverter.convertFiles();

        const mdPath = 'index/test-image.png.md';
        const original = await fileAdapter.read(mdPath);
        const [, autoZone] = original.split(AUTOGENERATED_MARKER);
        await fileAdapter.modify(mdPath, `# Notes\n\nMy image note.\n\n${AUTOGENERATED_MARKER}${autoZone}`);

        // Bump source modified time so re-index triggers
        await new Promise(resolve => setTimeout(resolve, 3));
        const src = await fileAdapter.readBinary('test-image.png');
        await fileAdapter.createOrUpdateBinaryFile('test-image.png', src);
        await pngConverter.convertFiles();

        const result = await fileAdapter.read(mdPath);
        expect(result).toContain('My image note.');
        expect(result.indexOf('My image note.')).toBeLessThan(result.indexOf(AUTOGENERATED_MARKER));
    });

    it('does not modify index file when source image is unchanged', async () => {
        await createTestImageFile(fileAdapter, 'test-image.png');
        await new Promise(resolve => setTimeout(resolve, 3));
        await pngConverter.convertFiles();

        await new Promise(resolve => setTimeout(resolve, 3));

        const mdPath = 'index/test-image.png.md';
        const timeBefore = (await fileAdapter.getFiles()).find(f => f.path === mdPath)?.modifiedTime;

        await new Promise(resolve => setTimeout(resolve, 3));
        await pngConverter.convertFiles();

        const timeAfter = (await fileAdapter.getFiles()).find(f => f.path === mdPath)?.modifiedTime;
        expect(timeAfter).toBe(timeBefore);
    });

    it('uses full vault-relative path in embed and file link', async () => {
        await createTestImageFile(fileAdapter, 'sub folder/test-image.png', 'test-image.png');
        await pngConverter.convertFiles();

        const content = await fileAdapter.read('index/test-image.png.md');
        expect(content).toContain('File: [test-image.png](sub folder/test-image.png)');
        expect(content).toContain('![[sub folder/test-image.png#height=500]]');
    });

    it('produces output exactly matching the fixture file', async () => {
        await createTestImageFile(fileAdapter, 'test-image.png');
        await pngConverter.convertFiles();

        const actual = await fileAdapter.read('index/test-image.png.md');
        const expected = readTestFile('test-image.png.md');
        expect(actual).toEqual(expected);
    });
});
