import {beforeEach, describe, expect, it} from 'vitest';
import {CanvasService} from '../../src/service/CanvasService';
import {FileDaoImpl} from '../../src/dao/FileDaoImpl';
import {InMemoryFileAdapter} from '../dao/InMemoryFileAdapter';
import {readTestFile} from '../utils/testFileUtils';
import {AUTOGENERATED_MARKER} from '../../src/utils/constants';

const CANVAS_CONTENT = readTestFile('Test.canvas');

describe('FileDaoImpl deletion safety', () => {
	let fileAdapter: InMemoryFileAdapter;
	let fileDao: FileDaoImpl;

	beforeEach(() => {
		fileAdapter = new InMemoryFileAdapter();
		fileDao = new FileDaoImpl(fileAdapter);
	});

	it('deletes a file that contains the autogenerated marker', async () => {
		await fileDao.createOrUpdateFile('index/Test.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\nsome content`);
		await expect(fileDao.deleteFile('index/Test.canvas.md')).resolves.toBeUndefined();
		await expect(fileAdapter.read('index/Test.canvas.md')).rejects.toThrow();
	});

	it('refuses to delete a file that only contains old-format marker text', async () => {
		const oldContent = 'This index file enables Obsidian and its plugins to manage canvas files effectively. It ensures alias files for canvases appear in graphs and allows plugins compatible only with MD files to access these files.';
		await fileDao.createOrUpdateFile('index/OldFormat.canvas.md', oldContent);
		await expect(fileDao.deleteFile('index/OldFormat.canvas.md')).rejects.toThrow();
	});
});

describe('Integration Test: Orphan Detection', () => {
	let fileAdapter: InMemoryFileAdapter;
	let fileDao: FileDaoImpl;

	beforeEach(() => {
		fileAdapter = new InMemoryFileAdapter();
		fileDao = new FileDaoImpl(fileAdapter);
	});

	it('vault-root-relative — orphan in index/ is cleaned up (no regression)', async () => {
		await fileDao.createOrUpdateFile('Test.canvas', CANVAS_CONTENT);
		await fileDao.createOrUpdateFile('index/Test.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\ncontent`);

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			indexFolder: 'index',
		});

		await fileAdapter.delete('Test.canvas');
		await service.convertFiles();

		await expect(fileAdapter.read('index/Test.canvas.md')).rejects.toThrow();
	});

	it('../ — deleting the source removes the orphaned index file at vault root', async () => {
		await fileDao.createOrUpdateFile('attachments/Test.canvas', CANVAS_CONTENT);
		await fileDao.createOrUpdateFile('Test.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\ncontent`);

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			indexFolder: '../',
		});

		await fileAdapter.delete('attachments/Test.canvas');
		await service.convertFiles();

		await expect(fileAdapter.read('Test.canvas.md')).rejects.toThrow();
	});

	it('../ — two sources, one deleted → orphan removed, sibling index kept', async () => {
		await fileDao.createOrUpdateFile('attachments/A.canvas', CANVAS_CONTENT);
		await fileDao.createOrUpdateFile('attachments/B.canvas', CANVAS_CONTENT);
		await fileDao.createOrUpdateFile('A.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\ncontent`);
		await fileDao.createOrUpdateFile('B.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\ncontent`);

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			indexFolder: '../',
		});

		await fileAdapter.delete('attachments/B.canvas');
		await service.convertFiles();

		// B orphan removed, A kept
		await expect(fileAdapter.read('B.canvas.md')).rejects.toThrow();
		expect(await fileAdapter.read('A.canvas.md')).toBeDefined();
	});

	it('./index — deleting the source removes the orphan in the relative subfolder', async () => {
		await fileDao.createOrUpdateFile('attachments/Test.canvas', CANVAS_CONTENT);
		await fileDao.createOrUpdateFile('attachments/index/Test.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\ncontent`);

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			indexFolder: './index',
		});

		await fileAdapter.delete('attachments/Test.canvas');
		await service.convertFiles();

		await expect(fileAdapter.read('attachments/index/Test.canvas.md')).rejects.toThrow();
	});

	it('content-marker safety — user file with .canvas.md extension in output dir is not deleted', async () => {
		await fileDao.createOrUpdateFile('attachments/Test.canvas', CANVAS_CONTENT);
		await fileDao.createOrUpdateFile('Test.canvas.md', `${AUTOGENERATED_MARKER}\n# Transcript\ncontent`);

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			indexFolder: '../',
		});

		// User creates their own .canvas.md note at root (no content marker)
		await fileDao.createOrUpdateFile('MyNote.canvas.md', '# My own note, no marker here');

		await fileAdapter.delete('attachments/Test.canvas');
		await service.convertFiles();

		// Plugin-generated orphan deleted, user file untouched
		await expect(fileAdapter.read('Test.canvas.md')).rejects.toThrow();
		expect(await fileAdapter.read('MyNote.canvas.md')).toBe('# My own note, no marker here');
	});
});
